#This yml file was gleened from Andrew Huang's template and the following:
#https://www.geeksforgeeks.org/spring-boot-database-integration-jpa-hibernate-mysql-h2/
#https://www.geeksforgeeks.org/spring-boot-with-h2-database/
server:
  port: 9090
spring:
  application:
    name: JPARunTest
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update