spring:
  application:
    name: WebClient
  main:
    web-application-type: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    rest:
      base-path: http://localhost:9090